// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$OrderImpl _$$OrderImplFromJson(Map<String, dynamic> json) => _$OrderImpl(
      id: (json['id'] as num).toInt(),
      doctorId: json['doctor_id'] as String,
      orderDate: DateTime.parse(json['order_date'] as String),
      orderTotal: (json['order_total'] as num).toDouble(),
      collectionCharge: json['collection_charge'] as String,
      paidAmount: (json['paid_amount'] as num).toDouble(),
      orderStatus: $enumDecode(_$OrderStatusEnumMap, json['order_status']),
      paymentMode: json['payment_mode'] as String,
      txnId: json['txn_id'] as String?,
      bnkTxnId: json['bnk_txn_id'] as String?,
      razorOrderId: json['razor_order_id'] as String,
      couponCode: json['coupon_code'] as String?,
      couponData: json['coupon_data'] as String?,
      couponAmount: (json['coupon_amount'] as num).toDouble(),
      couponType: json['coupon_type'] as String,
      couponCbAmount: (json['coupon_cb_amount'] as num).toDouble(),
      scCouponId: json['sc_coupon_id'] as String?,
      scCouponAmount: (json['sc_coupon_amount'] as num).toDouble(),
      scCouponDone: (json['sc_coupon_done'] as num).toInt(),
      cbAmountDone: json['cb_amount_done'] as String,
      walletPaid: (json['wallet_paid'] as num).toDouble(),
      qrisCoinsPaid: (json['qris_coins_paid'] as num).toDouble(),
      qrisCoinsDone: json['qris_coins_done'] as String,
      paymentRespons: json['payment_respons'] as String?,
      productRecord: json['product_record'] as String?,
      bookingSlotDate: json['booking_slot_date'] as String,
      bookingSlotTime: json['booking_slot_time'] as String?,
      bookingPin: json['booking_pin'] as String,
      bookingAddress: json['booking_address'] as String,
      sampleType: json['sample_type'] as String,
      tubeType: json['tube_type'] as String,
      hardCopy: json['hard_copy'] as String,
      agentId: (json['agent_id'] as num).toInt(),
      agentDiscountAmt: (json['agent_discount_amt'] as num).toDouble(),
      headofficeCollection: json['headoffice_collection'] as String,
      referredBy: json['referred_by'] as String,
      doctorBookingSlotTime: json['doctor_booking_slot_time'] as String?,
      doctorBookingAddress: json['doctor_booking_address'] as String,
      invoice: json['invoice'] as String,
    );

Map<String, dynamic> _$$OrderImplToJson(_$OrderImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'doctor_id': instance.doctorId,
      'order_date': instance.orderDate.toIso8601String(),
      'order_total': instance.orderTotal,
      'collection_charge': instance.collectionCharge,
      'paid_amount': instance.paidAmount,
      'order_status': _$OrderStatusEnumMap[instance.orderStatus]!,
      'payment_mode': instance.paymentMode,
      'txn_id': instance.txnId,
      'bnk_txn_id': instance.bnkTxnId,
      'razor_order_id': instance.razorOrderId,
      'coupon_code': instance.couponCode,
      'coupon_data': instance.couponData,
      'coupon_amount': instance.couponAmount,
      'coupon_type': instance.couponType,
      'coupon_cb_amount': instance.couponCbAmount,
      'sc_coupon_id': instance.scCouponId,
      'sc_coupon_amount': instance.scCouponAmount,
      'sc_coupon_done': instance.scCouponDone,
      'cb_amount_done': instance.cbAmountDone,
      'wallet_paid': instance.walletPaid,
      'qris_coins_paid': instance.qrisCoinsPaid,
      'qris_coins_done': instance.qrisCoinsDone,
      'payment_respons': instance.paymentRespons,
      'product_record': instance.productRecord,
      'booking_slot_date': instance.bookingSlotDate,
      'booking_slot_time': instance.bookingSlotTime,
      'booking_pin': instance.bookingPin,
      'booking_address': instance.bookingAddress,
      'sample_type': instance.sampleType,
      'tube_type': instance.tubeType,
      'hard_copy': instance.hardCopy,
      'agent_id': instance.agentId,
      'agent_discount_amt': instance.agentDiscountAmt,
      'headoffice_collection': instance.headofficeCollection,
      'referred_by': instance.referredBy,
      'doctor_booking_slot_time': instance.doctorBookingSlotTime,
      'doctor_booking_address': instance.doctorBookingAddress,
      'invoice': instance.invoice,
    };

const _$OrderStatusEnumMap = {
  OrderStatus.success: 'success',
  OrderStatus.complete: 'complete',
  OrderStatus.cancel: 'cancel',
};
