// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtxqIquJ1U_j8mcy5JOBXutYkzQWkn29I',
    appId: '1:134756807625:web:057c573da44caf45b56e18',
    messagingSenderId: '134756807625',
    projectId: 'qris-79e5a',
    authDomain: 'qris-79e5a.firebaseapp.com',
    storageBucket: 'qris-79e5a.firebasestorage.app',
    measurementId: 'G-9LV2GL21LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-F_YqaC5peimCRsLcAFtheiPV4fYZkWE',
    appId: '1:134756807625:android:614da517e025a15ab56e18',
    messagingSenderId: '134756807625',
    projectId: 'qris-79e5a',
    storageBucket: 'qris-79e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLZdqQ74miPR8vPlF_CJbYz5KGdVCyEMw',
    appId: '1:134756807625:ios:eed31b0bee1f5397b56e18',
    messagingSenderId: '134756807625',
    projectId: 'qris-79e5a',
    storageBucket: 'qris-79e5a.firebasestorage.app',
    iosBundleId: 'com.qris.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLZdqQ74miPR8vPlF_CJbYz5KGdVCyEMw',
    appId: '1:134756807625:ios:5b8d3732b6152d09b56e18',
    messagingSenderId: '134756807625',
    projectId: 'qris-79e5a',
    storageBucket: 'qris-79e5a.firebasestorage.app',
    iosBundleId: 'com.qris.app.qrisHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtxqIquJ1U_j8mcy5JOBXutYkzQWkn29I',
    appId: '1:134756807625:web:a0f90a710d03ab36b56e18',
    messagingSenderId: '134756807625',
    projectId: 'qris-79e5a',
    authDomain: 'qris-79e5a.firebaseapp.com',
    storageBucket: 'qris-79e5a.firebasestorage.app',
    measurementId: 'G-WBL2D8X4X8',
  );

}