// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVIeuvw57I3z8tKWfvsx5OrKtPQxPBBpk',
    appId: '1:472053921463:web:9b3c574dd573bbbef77f32',
    messagingSenderId: '472053921463',
    projectId: 'qris-80854',
    authDomain: 'qris-80854.firebaseapp.com',
    storageBucket: 'qris-80854.firebasestorage.app',
    measurementId: 'G-9Y5P7JKEEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKJ2UXcNJ98hbWOhRXPkCW25juFiR7qFM',
    appId: '1:472053921463:android:ce0ffc5edd1f6e38f77f32',
    messagingSenderId: '472053921463',
    projectId: 'qris-80854',
    storageBucket: 'qris-80854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoU4xOg_rgIxx5wXMcjACX6xCEEdD70ss',
    appId: '1:472053921463:ios:3b28b384a9f71eadf77f32',
    messagingSenderId: '472053921463',
    projectId: 'qris-80854',
    storageBucket: 'qris-80854.firebasestorage.app',
    iosBundleId: 'com.qris.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoU4xOg_rgIxx5wXMcjACX6xCEEdD70ss',
    appId: '1:472053921463:ios:baca5cb789b12b1ff77f32',
    messagingSenderId: '472053921463',
    projectId: 'qris-80854',
    storageBucket: 'qris-80854.firebasestorage.app',
    iosBundleId: 'com.qris.app.qrisHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVIeuvw57I3z8tKWfvsx5OrKtPQxPBBpk',
    appId: '1:472053921463:web:1def402bf1f2f208f77f32',
    messagingSenderId: '472053921463',
    projectId: 'qris-80854',
    authDomain: 'qris-80854.firebaseapp.com',
    storageBucket: 'qris-80854.firebasestorage.app',
    measurementId: 'G-BM4TNVNSFB',
  );
}
