// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPq2Ck8VdwD9vjWchAPxUquuBaL9JoECU',
    appId: '1:1034566344192:web:867fef4ef1f0a90c1d02e5',
    messagingSenderId: '1034566344192',
    projectId: 'qris-ebdd4',
    authDomain: 'qris-ebdd4.firebaseapp.com',
    storageBucket: 'qris-ebdd4.firebasestorage.app',
    measurementId: 'G-V4VM9W74HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc7EFlJe9O8I0N-1AYRJqBm0uEfDWSxiI',
    appId: '1:1034566344192:android:e3252dfa249cc3fb1d02e5',
    messagingSenderId: '1034566344192',
    projectId: 'qris-ebdd4',
    storageBucket: 'qris-ebdd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALOnKXkLnBVnvjfY2Q1M3sCY43hA5jCso',
    appId: '1:1034566344192:ios:8fc83f0e0812a38c1d02e5',
    messagingSenderId: '1034566344192',
    projectId: 'qris-ebdd4',
    storageBucket: 'qris-ebdd4.firebasestorage.app',
    iosBundleId: 'com.qris.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALOnKXkLnBVnvjfY2Q1M3sCY43hA5jCso',
    appId: '1:1034566344192:ios:2ccf669fef00b14c1d02e5',
    messagingSenderId: '1034566344192',
    projectId: 'qris-ebdd4',
    storageBucket: 'qris-ebdd4.firebasestorage.app',
    iosBundleId: 'com.qris.app.qrisHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPq2Ck8VdwD9vjWchAPxUquuBaL9JoECU',
    appId: '1:1034566344192:web:8c1bc87d91f9c7a81d02e5',
    messagingSenderId: '1034566344192',
    projectId: 'qris-ebdd4',
    authDomain: 'qris-ebdd4.firebaseapp.com',
    storageBucket: 'qris-ebdd4.firebasestorage.app',
    measurementId: 'G-QKJ85NENB6',
  );

}