// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'qris_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$QrisConfigImpl _$$QrisConfigImplFromJson(Map<String, dynamic> json) =>
    _$QrisConfigImpl(
      id: (json['id'] as num).toInt(),
      phoneNumber: json['phone_number'] as String,
      whatsappNumber: json['whatsapp_number'] as String,
      address: json['address'] as String,
      map: json['map'] as String,
      headerLogo: json['header_logo'] as String,
      facebookLink: json['facebook_link'] as String,
      twitterLink: json['twitter_link'] as String,
      instagramLink: json['instagram_link'] as String,
      linkedinLink: json['linkedin_link'] as String,
      adminEmail: json['admin_email'] as String,
      adminPhone: json['admin_phone'] as String,
      favIcon: json['fav_icon'] as String,
      category: json['category'] as String,
      achievements: json['achievements'] as String,
      adBanner2: json['ad_banner_2'] as String,
      footerLogo: json['footer_logo'] as String,
      footerIntro: json['footer_intro'] as String,
      privacyAndPolicy: json['privacy_and_policy'] as String,
      termsAndConditions: json['terms_and_conditions'] as String,
      cancellationPolicy: json['cancellation_policy'] as String,
      timeRange: json['time_range'] as String?,
      disableDate: json['disable_date'] as String?,
      tCatRiskArea: json['t_cat_risk_area'] as String,
      tCatBadHabits: json['t_cat_bad_habits'] as String,
      wcbEnable: json['wcb_enable'] as String,
      wcbAmount: (json['wcb_amount'] as num).toDouble(),
      qcEnable: json['qc_enable'] as String,
      qcAmount: (json['qc_amount'] as num).toDouble(),
      qcUsedCoins: (json['qc_used_coins'] as num).toDouble(),
      qcMinCartAmt: json['qc_min_cart_amt'] as String,
      wcbMinorderValue: (json['wcb_minorder_value'] as num).toDouble(),
      scbEnable: json['scb_enable'] as String,
      scbAmount: (json['scb_amount'] as num).toDouble(),
      ccbEnable: json['ccb_enable'] as String,
    );

Map<String, dynamic> _$$QrisConfigImplToJson(_$QrisConfigImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'phone_number': instance.phoneNumber,
      'whatsapp_number': instance.whatsappNumber,
      'address': instance.address,
      'map': instance.map,
      'header_logo': instance.headerLogo,
      'facebook_link': instance.facebookLink,
      'twitter_link': instance.twitterLink,
      'instagram_link': instance.instagramLink,
      'linkedin_link': instance.linkedinLink,
      'admin_email': instance.adminEmail,
      'admin_phone': instance.adminPhone,
      'fav_icon': instance.favIcon,
      'category': instance.category,
      'achievements': instance.achievements,
      'ad_banner_2': instance.adBanner2,
      'footer_logo': instance.footerLogo,
      'footer_intro': instance.footerIntro,
      'privacy_and_policy': instance.privacyAndPolicy,
      'terms_and_conditions': instance.termsAndConditions,
      'cancellation_policy': instance.cancellationPolicy,
      'time_range': instance.timeRange,
      'disable_date': instance.disableDate,
      't_cat_risk_area': instance.tCatRiskArea,
      't_cat_bad_habits': instance.tCatBadHabits,
      'wcb_enable': instance.wcbEnable,
      'wcb_amount': instance.wcbAmount,
      'qc_enable': instance.qcEnable,
      'qc_amount': instance.qcAmount,
      'qc_used_coins': instance.qcUsedCoins,
      'qc_min_cart_amt': instance.qcMinCartAmt,
      'wcb_minorder_value': instance.wcbMinorderValue,
      'scb_enable': instance.scbEnable,
      'scb_amount': instance.scbAmount,
      'ccb_enable': instance.ccbEnable,
    };
